version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      bundler_version:
        type: string
        default: 2.4.5
      ruby_type:
        type: string
        default: ruby
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
      ruby_type: << parameters.ruby_type >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    working_directory: ~/project
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libgmp-dev

      - samvera/cached_checkout

      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      # Rails 8.1
      - bundle_and_test:
          name: ruby4-0_rails8-1
          ruby_version: 4.0.1
          rails_version: 8.1.2
      # Rails 8.0
      - bundle_and_test:
          name: ruby3-4_rails8-0
          ruby_version: 3.4.4
          rails_version: 8.0.2
      # Rails 7.2
      - bundle_and_test:
          name: ruby3-3_rails7-2
          ruby_version: 3.3.4
          rails_version: 7.2.0

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main

    jobs:
      # Rails 8.1
      - bundle_and_test:
          name: ruby4-0_rails8-1
          ruby_version: 4.0.1
          rails_version: 8.1.2
      # Rails 8.0
      - bundle_and_test:
          name: ruby3-4_rails8-0
          ruby_version: 3.4.4
          rails_version: 8.0.2
      # Rails 7.2
      - bundle_and_test:
          name: ruby3-3_rails7-2
          ruby_version: 3.3.4
          rails_version: 7.2.0
